<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4f072a5e-05a3-47eb-a9f0-3e1b731b2965</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_5_madame</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav\ nav-pills\ nav-stacked"] &gt; li:nth-child(3) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'(5)
            MADAME')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>(5)
        MADAME</value>
        <webElementGuid>8017f7e5-1c74-42c5-9599-c39de039cf10</webElementGuid>
    </webElementProperties>
</WebElementEntity>