<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3dc6f461-3002-4f88-9622-6e2d49a2ef5a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_dress</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#Women li:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'DRESS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>DRESS</value>
        <webElementGuid>8017f7e5-1c74-42c5-9599-c39de039cf10</webElementGuid>
    </webElementProperties>
</WebElementEntity>